### ISSUE TITLE
Morning session team 13/01/23

### ISSUE THREAD

**Issue by jorgeabrahan** [anas599/Awsome-Books#4]
### Highlights
✅ Clean code
✅ Great Git Flow
✅ Code is working

### Things you can improve
- After adding the book, in order to improve the user experience you can reset() the form to clean all the input values and you can also focus() the input to insert the title. That way users will be able to add the other book right away.
- When loading the books from local storage you're not showing the text "Title:", but when you add a new book it has the "Title:" text, so you should either decide if you want to leave it or not and follow the same guidelines in both cases.
- Consider using a function to create a unique ID for each book instead of using the array length as it might get confusing or cause some issues in your code.

**Comment by edahigure** [comment]
createId(tokenLen = 16) {
    let id = '';
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    for (let i = 0; i < tokenLen; i += 1) {
      id += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    this.id = id;
  }

**Comment by SFarida** [comment]
Clean code, I have nothing more to add.
